version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_gpu
    container_name: voice-ai_app
    command: bash -c "python3 main.py"
    volumes:
      - ./app:/app
      - data:/root/nltk_data
    ports:
      - 8000:8000
      - 8888:8888
    restart: always
    privileged: true
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
volumes:
  data:
