version: "3.9"
services:
  app:
    build: .
    container_name: voice-ai_app
    command: bash -c "python main.py"
    volumes:
      - ./app:/app
      - data:/root/nltk_data
    ports:
      - 8000:8000
    restart: always
    privileged: true
    tty: true
    stdin_open: true
volumes:
  data:
