version: "3.9"
services:
  app:
    build: .
    container_name: voice-ai_app
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    restart: always
    privileged: true
    tty: true
    stdin_open: true